#
# Created by CC (deng you hua | cworld1000@gmail.com) on 2021/09/12
# https://github.com/ccworld1000/CCCanvas.Plane/CCCanvas.Plane.OC
#

platform :ios, '10.0'

target 'CCCanvas.Plane.OC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CCCanvas.Plane.OC
  # https://github.com/ccworld1000/CCCanvas
  pod 'CCCanvas'

end

